import { createGeneratedSourceExportFilename } from "./generated-source-export";
import type { GeneratedComponentVersionEntry } from "../shared/generated-version-contract";

export const PORTABLE_COMPONENT_BUNDLE_BLOB_TYPE = "application/zip";
export const PORTABLE_COMPONENT_BUNDLE_FILE_COUNT = 3;
export const PORTABLE_COMPONENT_BUNDLE_DIRECTORY_COUNT = 0;
export const PORTABLE_COMPONENT_BUNDLE_MAX_SOURCE_BYTES = 240_000;
export const PORTABLE_COMPONENT_BUNDLE_MAX_PATH_BYTES = 128;
export const PORTABLE_COMPONENT_BUNDLE_MAX_UNCOMPRESSED_BYTES = 241_024;
export const PORTABLE_COMPONENT_BUNDLE_MAX_ZIP_BYTES = 242_048;

export type PortableComponentBundleErrorCode =
  | "unsafe_filename"
  | "path_too_long"
  | "source_too_large"
  | "total_uncompressed_too_large"
  | "final_zip_too_large"
  | "zip32_numeric_overflow";

export type PortableComponentBundleResult =
  | {
      ok: true;
      value: {
        filename: string;
        bytes: Uint8Array;
        blobType: typeof PORTABLE_COMPONENT_BUNDLE_BLOB_TYPE;
      };
    }
  | {
      ok: false;
      code: PortableComponentBundleErrorCode;
      message: string;
    };

const ZIP32_STORE_METHOD = 0;
const ZIP32_GENERAL_PURPOSE_FLAGS = 0x0800;
const ZIP32_VERSION_NEEDED = 20;
const ZIP32_VERSION_MADE_BY = 0x0314;
const ZIP32_INTERNAL_ATTRIBUTES = 0x0000;
const ZIP32_EXTERNAL_ATTRIBUTES = 0x81A40000;
const ZIP32_DOS_DATE = 0x0021;
const ZIP32_DOS_TIME = 0x0000;
const ZIP32_LOCAL_FILE_HEADER_SIGNATURE = 0x04034b50;
const ZIP32_CENTRAL_DIRECTORY_HEADER_SIGNATURE = 0x02014b50;
const ZIP32_END_OF_CENTRAL_DIRECTORY_SIGNATURE = 0x06054b50;
const ZIP32_LOCAL_FILE_HEADER_LENGTH = 30;
const ZIP32_CENTRAL_DIRECTORY_HEADER_LENGTH = 46;
const ZIP32_END_OF_CENTRAL_DIRECTORY_LENGTH = 22;
const ZIP32_FIELD_MAX_UINT16 = 0xffff;
const ZIP32_FIELD_MAX_UINT32 = 0xffffffff;
const CRC32_INITIAL_VALUE = 0xffffffff;
const CRC32_FINAL_XOR = 0xffffffff;
const CRC32_REFLECTED_POLYNOMIAL = 0xEDB88320;

const README_PATH = "README.md";
const MANIFEST_PATH = "element-catcher.json";
const SOURCE_DIR = "src/";
const encoder = new TextEncoder();

export const PORTABLE_COMPONENT_BUNDLE_README = `# Element Catcher Component Bundle

This bundle contains component source generated by Element Catcher.

Review the source before use. Dependencies, package.json, Tailwind configuration, build configuration, and application scaffolding are not included.

This bundle is not guaranteed to compile, render correctly, be secure, or be production-ready.
`;

type ZipEntry = Readonly<{
  path: string;
  pathBytes: Uint8Array;
  bytes: Uint8Array;
  crc32: number;
  localHeaderOffset: number;
}>;

type PendingEntry = Readonly<{
  path: string;
  pathBytes: Uint8Array;
  bytes: Uint8Array;
  crc32: number;
}>;

export function createPortableComponentBundle(entry: GeneratedComponentVersionEntry): PortableComponentBundleResult {
  const sourceFilename = createGeneratedSourceExportFilename(entry.value.componentName);
  if (!sourceFilename.ok) {
    return bundleError("unsafe_filename", "Component name is not safe for portable bundle export.");
  }

  const zipFilename = sourceFilename.value.replace(/\.tsx$/u, ".zip");
  if (zipFilename === sourceFilename.value) {
    return bundleError("unsafe_filename", "Component name is not safe for portable bundle export.");
  }

  const sourcePath = `${SOURCE_DIR}${sourceFilename.value}`;
  const sourceBytes = encoder.encode(entry.value.code);
  if (sourceBytes.byteLength > PORTABLE_COMPONENT_BUNDLE_MAX_SOURCE_BYTES) {
    return bundleError("source_too_large", "Generated source is too large for portable bundle export.");
  }

  const manifestResult = createBundleManifest(entry.value.componentName, sourcePath);
  if (!manifestResult.ok) {
    return manifestResult;
  }

  const readmeEntry = createPendingEntry(README_PATH, encoder.encode(PORTABLE_COMPONENT_BUNDLE_README));
  if (!readmeEntry.ok) {
    return readmeEntry;
  }
  const manifestEntry = createPendingEntry(MANIFEST_PATH, encoder.encode(manifestResult.value));
  if (!manifestEntry.ok) {
    return manifestEntry;
  }
  const sourceEntry = createPendingEntry(sourcePath, sourceBytes);
  if (!sourceEntry.ok) {
    return sourceEntry;
  }

  const entries = [readmeEntry.value, manifestEntry.value, sourceEntry.value];
  const totalUncompressedBytes = entries.reduce((total, pending) => total + pending.bytes.byteLength, 0);
  if (totalUncompressedBytes > PORTABLE_COMPONENT_BUNDLE_MAX_UNCOMPRESSED_BYTES) {
    return bundleError("total_uncompressed_too_large", "Portable bundle contents are too large.");
  }

  const zipResult = writePortableBundleZip(entries);
  if (!zipResult.ok) {
    return zipResult;
  }
  if (zipResult.value.byteLength > PORTABLE_COMPONENT_BUNDLE_MAX_ZIP_BYTES) {
    return bundleError("final_zip_too_large", "Portable bundle ZIP is too large.");
  }

  return {
    ok: true,
    value: {
      filename: zipFilename,
      bytes: zipResult.value,
      blobType: PORTABLE_COMPONENT_BUNDLE_BLOB_TYPE
    }
  };
}

function createBundleManifest(componentName: string, entryPath: string): PortableComponentBundleResult | { ok: true; value: string } {
  return {
    ok: true,
    value: `{
  "formatVersion": 1,
  "framework": "react",
  "styling": "tailwind",
  "componentName": ${JSON.stringify(componentName)},
  "entryPath": ${JSON.stringify(entryPath)}
}
`
  };
}

function createPendingEntry(path: string, bytes: Uint8Array): PortableComponentBundleResult | { ok: true; value: PendingEntry } {
  if (!isSafeInternalPath(path)) {
    return bundleError("unsafe_filename", "Portable bundle entry path is not safe.");
  }
  const pathBytes = encoder.encode(path);
  if (pathBytes.byteLength > PORTABLE_COMPONENT_BUNDLE_MAX_PATH_BYTES) {
    return bundleError("path_too_long", "Portable bundle entry path is too long.");
  }
  return {
    ok: true,
    value: {
      path,
      pathBytes,
      bytes,
      crc32: calculateCrc32(bytes)
    }
  };
}

function writePortableBundleZip(pendingEntries: PendingEntry[]): PortableComponentBundleResult | { ok: true; value: Uint8Array } {
  if (pendingEntries.length !== PORTABLE_COMPONENT_BUNDLE_FILE_COUNT) {
    return bundleError("zip32_numeric_overflow", "Portable bundle ZIP entry count is invalid.");
  }

  let localBytesLength = 0;
  const entries: ZipEntry[] = [];
  for (const pending of pendingEntries) {
    if (!fitsZip32(pending.pathBytes.byteLength) || !fitsZip32(pending.bytes.byteLength) || !fitsZip32(localBytesLength)) {
      return bundleError("zip32_numeric_overflow", "Portable bundle ZIP field exceeded ZIP32 limits.");
    }
    entries.push({ ...pending, localHeaderOffset: localBytesLength });
    localBytesLength += ZIP32_LOCAL_FILE_HEADER_LENGTH + pending.pathBytes.byteLength + pending.bytes.byteLength;
  }

  const centralDirectoryOffset = localBytesLength;
  const centralDirectorySize = entries.reduce(
    (total, entry) => total + ZIP32_CENTRAL_DIRECTORY_HEADER_LENGTH + entry.pathBytes.byteLength,
    0
  );
  const finalLength = localBytesLength + centralDirectorySize + ZIP32_END_OF_CENTRAL_DIRECTORY_LENGTH;

  if (
    !fitsZip32(centralDirectoryOffset) ||
    !fitsZip32(centralDirectorySize) ||
    !fitsZip32(finalLength) ||
    entries.length > ZIP32_FIELD_MAX_UINT16
  ) {
    return bundleError("zip32_numeric_overflow", "Portable bundle ZIP field exceeded ZIP32 limits.");
  }
  if (finalLength > PORTABLE_COMPONENT_BUNDLE_MAX_ZIP_BYTES) {
    return bundleError("final_zip_too_large", "Portable bundle ZIP is too large.");
  }

  const output = new Uint8Array(finalLength);
  const view = new DataView(output.buffer);
  let offset = 0;

  for (const entry of entries) {
    offset = writeLocalFileHeader(view, offset, entry);
    output.set(entry.pathBytes, offset);
    offset += entry.pathBytes.byteLength;
    output.set(entry.bytes, offset);
    offset += entry.bytes.byteLength;
  }

  for (const entry of entries) {
    offset = writeCentralDirectoryFileHeader(view, offset, entry);
    output.set(entry.pathBytes, offset);
    offset += entry.pathBytes.byteLength;
  }

  offset = writeEndOfCentralDirectory(view, offset, entries.length, centralDirectorySize, centralDirectoryOffset);
  if (offset !== finalLength) {
    return bundleError("zip32_numeric_overflow", "Portable bundle ZIP length was inconsistent.");
  }

  return { ok: true, value: output };
}

function writeLocalFileHeader(view: DataView, offset: number, entry: ZipEntry) {
  view.setUint32(offset, ZIP32_LOCAL_FILE_HEADER_SIGNATURE, true);
  view.setUint16(offset + 4, ZIP32_VERSION_NEEDED, true);
  view.setUint16(offset + 6, ZIP32_GENERAL_PURPOSE_FLAGS, true);
  view.setUint16(offset + 8, ZIP32_STORE_METHOD, true);
  view.setUint16(offset + 10, ZIP32_DOS_TIME, true);
  view.setUint16(offset + 12, ZIP32_DOS_DATE, true);
  view.setUint32(offset + 14, entry.crc32, true);
  view.setUint32(offset + 18, entry.bytes.byteLength, true);
  view.setUint32(offset + 22, entry.bytes.byteLength, true);
  view.setUint16(offset + 26, entry.pathBytes.byteLength, true);
  view.setUint16(offset + 28, 0, true);
  return offset + ZIP32_LOCAL_FILE_HEADER_LENGTH;
}

function writeCentralDirectoryFileHeader(view: DataView, offset: number, entry: ZipEntry) {
  view.setUint32(offset, ZIP32_CENTRAL_DIRECTORY_HEADER_SIGNATURE, true);
  view.setUint16(offset + 4, ZIP32_VERSION_MADE_BY, true);
  view.setUint16(offset + 6, ZIP32_VERSION_NEEDED, true);
  view.setUint16(offset + 8, ZIP32_GENERAL_PURPOSE_FLAGS, true);
  view.setUint16(offset + 10, ZIP32_STORE_METHOD, true);
  view.setUint16(offset + 12, ZIP32_DOS_TIME, true);
  view.setUint16(offset + 14, ZIP32_DOS_DATE, true);
  view.setUint32(offset + 16, entry.crc32, true);
  view.setUint32(offset + 20, entry.bytes.byteLength, true);
  view.setUint32(offset + 24, entry.bytes.byteLength, true);
  view.setUint16(offset + 28, entry.pathBytes.byteLength, true);
  view.setUint16(offset + 30, 0, true);
  view.setUint16(offset + 32, 0, true);
  view.setUint16(offset + 34, 0, true);
  view.setUint16(offset + 36, ZIP32_INTERNAL_ATTRIBUTES, true);
  view.setUint32(offset + 38, ZIP32_EXTERNAL_ATTRIBUTES, true);
  view.setUint32(offset + 42, entry.localHeaderOffset, true);
  return offset + ZIP32_CENTRAL_DIRECTORY_HEADER_LENGTH;
}

function writeEndOfCentralDirectory(
  view: DataView,
  offset: number,
  entryCount: number,
  centralDirectorySize: number,
  centralDirectoryOffset: number
) {
  view.setUint32(offset, ZIP32_END_OF_CENTRAL_DIRECTORY_SIGNATURE, true);
  view.setUint16(offset + 4, 0, true);
  view.setUint16(offset + 6, 0, true);
  view.setUint16(offset + 8, entryCount, true);
  view.setUint16(offset + 10, entryCount, true);
  view.setUint32(offset + 12, centralDirectorySize, true);
  view.setUint32(offset + 16, centralDirectoryOffset, true);
  view.setUint16(offset + 20, 0, true);
  return offset + ZIP32_END_OF_CENTRAL_DIRECTORY_LENGTH;
}

function calculateCrc32(bytes: Uint8Array) {
  let crc = CRC32_INITIAL_VALUE;
  for (const byte of bytes) {
    crc ^= byte;
    for (let bit = 0; bit < 8; bit += 1) {
      crc = (crc >>> 1) ^ (CRC32_REFLECTED_POLYNOMIAL & -(crc & 1));
    }
  }
  return (crc ^ CRC32_FINAL_XOR) >>> 0;
}

function isSafeInternalPath(path: string) {
  if (
    path.length === 0 ||
    path.startsWith("/") ||
    path.endsWith("/") ||
    path.includes("\\") ||
    /[\u0000-\u001f\u007f-\u009f\u200c-\u200f\u202a-\u202e\u2060-\u206f\ufeff?#]/u.test(path)
  ) {
    return false;
  }
  const segments = path.split("/");
  return segments.every((segment) => segment.length > 0 && segment !== "." && segment !== "..");
}

function fitsZip32(value: number) {
  return Number.isSafeInteger(value) && value >= 0 && value <= ZIP32_FIELD_MAX_UINT32;
}

function bundleError(code: PortableComponentBundleErrorCode, message: string): PortableComponentBundleResult {
  return { ok: false, code, message };
}
